// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { SUPABASE_CONFIG } from '@/config/constants';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Regular client for authenticated users
export const supabase = createClient<Database>(
  SUPABASE_CONFIG.url, 
  SUPABASE_CONFIG.publishableKey,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);

// Service role client for admin operations
export const supabaseAdmin = createClient<Database>(
  SUPABASE_CONFIG.url,
  SUPABASE_CONFIG.serviceRoleKey || SUPABASE_CONFIG.publishableKey,
  {
    auth: {
      persistSession: false,
    }
  }
);